spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: admin
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    show-sql: true

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  security:
    user:
      name: admin
      password: 9a756023-7d7a-49ad-9b0b-544f35b53e5a
  server:
    port: 8081

    server:
      servlet:
        context-path: /api
  servers:
    url: /swagger-ui.html
    description: springdoc.api-docs.path=/api-docs
