CREATE TABLE people(
    uniqid NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name VARCHAR(100),
    last_names VARCHAR(100),
    identity VARCHAR(100),
    date_of_birth date,
    place_of_birth VARCHAR(100),
    height FLOAT,
    rh VARCHAR(100),
    t_sex VARCHAR(100),
    expedition_date VARCHAR(100),
    expedition_place VARCHAR(100),

    PRIMARY KEY(uniqid)
);